name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      # - uses: erlef/setup-beam@v1
      #   with:
      #     otp-version: "26.0.2"
      #     # Ensure you update the bin/download-compiler Gleam version to match this
      #     gleam-version: "1.5.1"
      #     rebar3-version: "3"

      - uses: cachix/install-nix-action@v26
      - uses: DeterminateSystems/magic-nix-cache-action@v4
      - run: ./bin/download-compiler
      - run: glistix deps download
        shell: nix develop --command bash -e {0}
      - run: glistix format --check src test
        shell: nix develop --command bash -e {0}
      - name: Generate Nix files
        run: glistix build --target nix
        shell: nix develop --command bash -e {0}
      - run: glistix test
        shell: nix develop --command bash -e {0}
      - run: glistix run
        shell: nix develop --command bash -e {0}
